# goal sent to client
string obtaingun #which action baxter needs to do
string aimgun
---
# result sent to server
bool guncomplete #did the action complete successfully
bool aimcomplete
---
# feedback
string gunstate
string aimstate
