# goal sent to client
string gunaction #which action baxter needs to do
string aimaction
string triggeraction
string fireaction
string finalaction
---
# result sent to server
bool completion #did the action complete successfully
---
# feedback
string feedback_state
