#!/usr/bin/env python
import rospy

import roslib
import sys
import time

import baxter_interface

import cv2
import cv_bridge
from sensor_msgs.msg import Image

import actionlib
import moveit_commander

roslib.load_manifest('terminator')

import terminator.msg


"""
Integrates all the nodes
Receives messages to know the current state of the robot
Sends messages to transition between different states of the robot to drive the motion sequence

use action server
  goals are executed on server side
  goals are requested on client side
"""

def enableBaxter():
#    baxter_interface.RobotEnable().enable()
#    rospy.sleep(0.25)
    face = '/config/time_cop.jpg'

    # joint_state_topic = ['joint_states:=/robot/joint_states']
    # moveit_commander.roscpp_initialize(joint_state_topic)
    #
    # calibrateGripper('left')
    # calibrateGripper('right')

    print("Baxter is enabled")

def calibrateGripper(side):
    """
    SCRIPT

    Define gripper
    Reboot gripper
    Calibrate gripper
    Open gripper
    """

    gripper = Gripper(side, CHECK_VERSION)
    gripper.reboot()
    gripper.calibrate()
    gripper.open()

def main():

    # get baxter to move to a good initial pose for its arms

    pickgunclient = actionlib.SimpleActionClient('guncommander', terminator.msg.CommandsAction)
    aimclient = actionlib.SimpleActionClient('aimcommander', terminator.msg.CommandsAction)
    triggerclient = actionlib.SimpleActionClient('triggercommander', terminator.msg.CommandsAction)
    fireclient = actionlib.SimpleActionClient('firecommander', terminator.msg.CommandsAction)
    finalclient = actionlib.SimpleActionClient('finalcommander', terminator.msg.CommandsAction)

    print("next")
    pickgunclient.wait_for_server()
    print("received")

    # Pick up the gun using the left hand
    goal = terminator.msg.CommandsGoal(actionname="get_gun")
    pickgunclient.send_goal(goal)
    pickgunclient.wait_for_result()
    gotgun = pickgunclient.get_result() #bool if baxter retrieved gun or not

    print(pickgunclient.get_result())
    # Move left hand to be in line with the target
    if gotgun.completion == True:
        print("Baxter is armed")
        time.sleep(5)

        pickgunclient.stop_tracking_goal()
        pickgunclient.cancel_all_goals()

        print("canceled getting gun")

    #if True:

        aimgoal = terminator.msg.CommandsGoal(actionname='aim_gun')

        #client.accept_new_goal()

        aimclient.send_goal(aimgoal)
        aimclient.wait_for_result()
        aimed = aimclient.get_result()

        print(aimed.completion)

        while aimed.completion != True:
            aimclient.send_goal(aimgoal)
            aimclient.wait_for_result()
            aimed = aimclient.get_result()


        # Right hand moves to the trigger
        if aimed.completion == True:
            print("Baxter has acquired target and is aiming")
            time.sleep(5)

            aimclient.stop_tracking_goal()
            aimclient.cancel_all_goals()

    #if True:
         #if True:

            print("canceled aiming")


            triggerclient.wait_for_server()


            triggergoal = terminator.msg.CommandsGoal(actionname='moveto_trigger')
            triggerclient.send_goal(triggergoal)
            triggerclient.wait_for_result()
            ontrigger = triggerclient.get_result()

            print(ontrigger.completion)

            # User confirmation to fire
            if ontrigger.completion == True:
                print("Baxter awaiting command to fire")

                time.sleep(5)

                triggerclient.stop_tracking_goal()
                triggerclient.cancel_all_goals()

                print("canceled getting to trigger")



                # Pull the trigger
                pulled = False
                while pulled != True:
                    user_input = raw_input("Permission to fire? Yes or No:   ")
                    if (user_input.lower() == "yes" or user_input.lower() == "y"):
                        firegoal = terminator.msg.CommandsGoal(actionname='fire')
                        fireclient.send_goal(firegoal)
                        fireclient.wait_for_result()
                        fired = fireclient.get_result()

                        if fired.completion == True:
                        #if True:
                            print("Baxter has successfully shot (or attempted to)")
                            pulled = True

                            time.sleep(5)

                            fireclient.stop_tracking_goal()
                            fireclient.cancel_all_goals()

                            print("canceled fire")

                            finalgoal = terminator.msg.CommandsGoal(actionname='finalpose')
                            finalclient.send_goal(finalgoal)
                            finalclient.wait_for_result()
                            finalpose = finalclient.get_result()

                            print(finalpose.completion)

                            finalclient.stop_tracking_goal()
                            finalclient.cancel_all_goals()
                            print("shooting complete")

                    else:
                        print("Please select another option")

def initPos():
    # move both arms to a good position before the initial poses
    left = baxter_interface.Limb('left')
    right = baxter_interface.Limb('right')

    lcmd ={'left_s0':0.764689422761,'left_s1':-0.143810698864,'left_e0':-0.190213617698,'left_e1':1.71345654007,'left_w0':1.52822835993,'left_w1':-1.4684031092,'left_w2':0.0383495196971} #,4.51127815247}
    rcmd = {'right_s0':-0.353582571608,'right_s1':-0.676869022654,'right_e0':0.20133497841,'right_e1':1.70156818896,'right_w0':-2.16828184368,'right_w1':-1.5704128316,'right_w2':0.245820421259} #,95.4983901978}

    left.move_to_joint_positions(lcmd)
    right.move_to_joint_positions(rcmd)

    print("Using Forward Kinematics To Initialize Pose")

if __name__ == '__main__':
    try:
        rospy.init_node("commander_client_py")
        enableBaxter()
        initPos()
        main()
    except rospy.ROSInterruptException:
        print("program interrupted before baxter could shoot")
