#!/usr/bin/env python
import rospy

import roslib
import sys
import time

import actionlib

roslib.load_manifest('terminator')

import terminator.msg


"""
Integrates all the nodes
Receives messages to know the current state of the robot
Sends messages to transition between different states of the robot to drive the motion sequence

use action server
  goals are executed on server side
  goals are requested on client side
"""

def enableBaxter():
#    baxter_interface.RobotEnable().enable()
#    rospy.sleep(0.25)
    print("Baxter is enabled")


def main():

    client = actionlib.SimpleActionClient('commander', terminator.msg.CommandsAction)

    print("next")
    client.wait_for_server()
    print("received")

    # Pick up the gun using the left hand
    goal = terminator.msg.CommandsGoal(gunaction="get_gun")
    client.send_goal(goal)
    client.wait_for_result()
    gotgun = client.get_result() #bool if baxter retrieved gun or not

    print(client.get_result())
    # Move left hand to be in line with the target
    if gotgun.completion == True:
        print("Baxter is armed")
        time.sleep(5)

        client.stop_tracking_goal()
        client.cancel_all_goals()

        print("canceled getting gun")

    #if True:

        aimgoal = terminator.msg.CommandsGoal(aimaction='aim_gun')

        #client.accept_new_goal()

        client.send_goal(aimgoal)
        client.wait_for_result()
        aimed = client.get_result()

        print(aimed.completion)
        print("yay - fired!!!")

        while aimed.completion != True:
            client.send_goal(aimgoal)
            client.wait_for_result()
            aimed = client.get_result()


        # Right hand moves to the trigger
        if aimed.completion == True:
            print("Baxter has acquired target and is aiming")
            time.sleep(5)

            client.stop_tracking_goal()
            client.cancel_all_goals()

    #if True:
        #if True:

            print("canceled aiming")


            client.wait_for_server()


            triggergoal = terminator.msg.CommandsGoal(triggeraction='moveto_trigger')
            client.send_goal(triggergoal)
            client.wait_for_result()
            ontrigger = client.get_result()

            print(ontrigger.completion)

            # User confirmation to fire
            if ontrigger.completion == True:
                print("Baxter awaiting command to fire")

                time.sleep(5)

                client.stop_tracking_goal()
                client.cancel_all_goals()

                print("canceled getting to trigger")



                # Pull the trigger
                pulled = False
                while pulled != True:
                    user_input = raw_input("Permission to fire? Yes or No:   ")
                    if (user_input.lower() == "yes" or user_input.lower() == "y"):
                        firegoal = terminator.msg.CommandsGoal(fireaction='fire')
                        client.send_goal(firegoal)
                        client.wait_for_result()
                        fired = client.get_result()

                        if fired.completion == True:
                            print("Baxter has successfully shot (or attempted to)")
                            pulled = True

                            time.sleep(5)

                            client.stop_tracking_goal()
                            client.cancel_all_goals()

                            finalgoal = terminator.msg.CommandsGoal(finalaction='finalpose')
                            client.send_goal(finalgoal)
                            client.wait_for_result()
                            finalresult = client.get_result()

                            print(finalresult.completion)


                            print("canceled moving to final pose. Done")
                    else:
                        print("Please select another option")



if __name__ == '__main__':
    try:
        rospy.init_node("commander_client_py")
        enableBaxter()
        main()
    except rospy.ROSInterruptException:
        print("program interrupted before baxter could shoot")
