#!/usr/bin/env python

"""

PUBLSIHERS:
    +

SUBSCRIBERS:
    +
"""

from __future__ import division

import sys
import copy
import rospy
import roslib

import actionlib
roslib.load_manifest('terminator')
import terminator.msg



class RightArm(object):
    # create messages that are used to publish feedback/result
    _feedback = terminator.msg.CommandsFeedback()
    _result = terminator.msg.CommandsResult()

    def __init__(self):
        print("init")
        self._as = actionlib.SimpleActionServer("commander", terminator.msg.CommandsAction, self.execute_cb, auto_start = False)
        self._as.start()
        print("made it")

    def execute_cb(self, goal):
        print("in cb")
        # helper variables
        r = rospy.Rate(1)
        success = True

        if goal.actionname == "aim_gun":
            if self._as.is_preempt_requested():
                rospy.loginfo('%s: Preempted' % self._action_name)
                self._as.set_preempted()
                success = False
            print("yay")
        else:
            print(":(")
            success = False

        if success:
            self._result.completion = True
            rospy.loginfo('%s: Succeeded' % 'right_arm')
            self._as.set_succeeded(self._result)

        rospy.spin()


if __name__ == '__main__':
    rospy.init_node('right_arm')
    server = RightArm()









#
















#
