#!/usr/bin/env python

"""

PUBLSIHERS:
    +

SUBSCRIBERS:
    +
"""

from __future__ import division

import sys
import copy
import rospy
import roslib

import actionlib
roslib.load_manifest('terminator')
import terminator.msg



class RightArm(object):
    # create messages that are used to publish feedback/result
    _feedback = terminator.msg.CommandsFeedback()
    _result = terminator.msg.CommandsResult()


    def __init__(self):
        print("init")
        self._as = actionlib.SimpleActionServer("commander", terminator.msg.CommandsAction, execute_cb=self.execute_cb, auto_start = False)

        self._as.start()
        print("trigger started")
        print("fire started")

    def execute_cb(self, goal):
        print("in trigger cb")
        # helper variables
        r = rospy.Rate(1)
        success = True

        if goal.triggeraction == "moveto_trigger":
            if self._as.is_preempt_requested():
                rospy.loginfo('%s: Preempted' % 'right_arm got trigger')
                self._as.set_preempted()
                success = False
            print("yay - got right arm to trigger")

            if success:
                self._result.completion = True
                rospy.loginfo('%s: Succeeded' % 'right_arm got trigger')
                self._as.set_succeeded(self._result)
            else:
                self._result.completion = False
                self._as.set_succeeded(self._result)

        else:
            print(":( - don't get right arm to trigger")
            success = False




        print("in trigger cb")
        # helper variables
        r = rospy.Rate(1)
        success = True

        if goal.fireaction == "fire":
            if self._as.is_preempt_requested():
                rospy.loginfo('%s: Preempted' % 'fired!')
                self._as.set_preempted()
                success = False
            print("yay - fired!!!")

            if success:
                self._result.completion = True
                rospy.loginfo('%s: Succeeded' % 'fired!')
                self._as.set_succeeded(self._result)
            else:
                self._result.completion = False
                self._as.set_succeeded(self._result)

        else:
            print(":( - didn't fire...")
            success = False

if __name__ == '__main__':
    rospy.init_node('right_arm')
    server = RightArm()
    rospy.spin()








#
















#
